FROM ruby:2.5
# Set timezone

RUN apt-get update && apt-get install -yq \
    chromium \
    git-core \
    xvfb \
    xsel \
    unzip

# chromeDriver v2.35
RUN wget -q "https://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip" -O /tmp/chromedriver.zip \
    && unzip /tmp/chromedriver.zip -d /usr/bin/ \
    && rm /tmp/chromedriver.zip

# xvfb - X server display
ADD xvfb-chromium /usr/bin/xvfb-chromium
RUN ln -s /usr/bin/xvfb-chromium /usr/bin/google-chrome \
    && chmod 777 /usr/bin/xvfb-chromium

# create symlinks to chromedriver and geckodriver (to the PATH)
RUN ln -s /usr/bin/chromium \
    && chmod 777 /usr/bin/chromium

RUN mkdir -p /app
WORKDIR /app

